basic:
  input_path: data/designed/description/ProDVa.json
  output_dir: example/description-guided
  dataset_type: DescriptionDataset
  visualize: True
  num_gpu: -1
  num_cpu: -1
  design_batch_size: 3
  deepgo_handler: ~/.conda/envs/PDF-DeepGO2/bin/python  # this may be changed, if you change the environment name or have a different conda path.

  
# Sequence
repeat:
  run: True
  compute_methods: ["RepN", "Repeat"]
  RepN: [2, 5]
bert_score: 
  run: True
  compute_models: [ESM2]
identity: 
  run: True
  thread_per_mmseqs: 16
perplexity:
  run: True
  compute_models: [ProGen2, ProtGPT2, RITA]


# Structure
foldability:
  run: True
tm_score:
  run: True
  tm_score_ex_path: tools/TMScore/TMscore


# Language Alignment
protrek_score: 
  run: True
  protrek_path: weights/ProTrek_650M_UniRef50
evollama_score:
  run: True
  evollama_path: weights/EvoLlama
ipr_score:
  run: True
  interpro_scan_ex_path: tools/InterProScan/interproscan/interproscan-5.75-106.0-64/interproscan.sh
  interpro_cache_path: .ipr_cache.json
go_score:
  run: True
  deepgo_weight_path: weights/DeepGO/data
retrieval_acc:
  run: True
  retrieval_difficulties: [Soft, Normal, Hard]

  
# Others
novelty:
  run: True
  novelties: [Sequence, Structure]
  mmseqs_ex_path: tools/MMseqs/bin/mmseqs
  foldseek_ex_path: tools/Foldseek/bin/foldseek
  mmseqs_targetdb_path: tools/MMseqs/db/uniprotdb_gpu
  foldseek_targetdb_path: tools/Foldseek/db/AlphaSwissGPU/AlphaG
diversity:
  run: True
  diversities: [Sequence, Structure]